// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIf9LyrWtXjq655ArH0yf9y3UloRWTrY4',
    appId: '1:570546906315:web:6351498cfedd8b1f79e74e',
    messagingSenderId: '570546906315',
    projectId: 'mappingr-d8942',
    authDomain: 'mappingr-d8942.firebaseapp.com',
    storageBucket: 'mappingr-d8942.firebasestorage.app',
    measurementId: 'G-B1W51DQ0W7',
  );

  // ── Web ──────────────────────────────────────────────────────────────────

  // ── Android ──────────────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6hVMw8ThViwPKH36Ph7isYQNKGz-ptHY',
    appId: '1:570546906315:android:74425553c661f93779e74e',
    messagingSenderId: '570546906315',
    projectId: 'mappingr-d8942',
    storageBucket: 'mappingr-d8942.firebasestorage.app',
  );

  // TODO: replace appId with the real value from google-services.json

  // ── iOS ──────────────────────────────────────────────────────────────────

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpxlas-blcwigh-w120kNvwy66pTr03Co',
    appId: '1:570546906315:ios:dd6efdfae06825a979e74e',
    messagingSenderId: '570546906315',
    projectId: 'mappingr-d8942',
    storageBucket: 'mappingr-d8942.firebasestorage.app',
    androidClientId: '570546906315-2pdujl9vfqtjcun1e7l78hk0gp3t4fdf.apps.googleusercontent.com',
    iosClientId: '570546906315-9scaqldmb8qc66bl26lugb67dghsocjt.apps.googleusercontent.com',
    iosBundleId: 'com.zingoo.app',
  );

  // TODO: replace appId with the real value from GoogleService-Info.plist

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIf9LyrWtXjq655ArH0yf9y3UloRWTrY4',
    appId: '1:570546906315:web:8303fe2deb5ffe8379e74e',
    messagingSenderId: '570546906315',
    projectId: 'mappingr-d8942',
    authDomain: 'mappingr-d8942.firebaseapp.com',
    storageBucket: 'mappingr-d8942.firebasestorage.app',
    measurementId: 'G-0V26M6K7PD',
  );

  // ── Windows (uses web config) ─────────────────────────────────────────────

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpxlas-blcwigh-w120kNvwy66pTr03Co',
    appId: '1:570546906315:ios:1841607a95d1515579e74e',
    messagingSenderId: '570546906315',
    projectId: 'mappingr-d8942',
    storageBucket: 'mappingr-d8942.firebasestorage.app',
    androidClientId: '570546906315-2pdujl9vfqtjcun1e7l78hk0gp3t4fdf.apps.googleusercontent.com',
    iosClientId: '570546906315-na5va7hli55po53o886mqpatfha4mvfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.playradar',
  );

}