// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSSAHPVAZ-fd4gJmsLji1GqLvft7ExKlg',
    appId: '1:408787402316:web:dcd1a5a610b54d078afee9',
    messagingSenderId: '408787402316',
    projectId: 'zingoo-823df',
    authDomain: 'zingoo-823df.firebaseapp.com',
    storageBucket: 'zingoo-823df.firebasestorage.app',
    measurementId: 'G-JEP7P48GH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaFCsz_nHf0U9mnG8A9KIM9KKjSS7XXVs',
    appId: '1:408787402316:android:93ef148d19bb79448afee9',
    messagingSenderId: '408787402316',
    projectId: 'zingoo-823df',
    storageBucket: 'zingoo-823df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTmqyrwORjbKtFFMaRoJhsUmXZoEVLmlU',
    appId: '1:408787402316:ios:3ceaeb7d8964e1e78afee9',
    messagingSenderId: '408787402316',
    projectId: 'zingoo-823df',
    storageBucket: 'zingoo-823df.firebasestorage.app',
    iosBundleId: 'com.zingoo.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSSAHPVAZ-fd4gJmsLji1GqLvft7ExKlg',
    appId: '1:408787402316:web:baf9e716bb8f22968afee9',
    messagingSenderId: '408787402316',
    projectId: 'zingoo-823df',
    authDomain: 'zingoo-823df.firebaseapp.com',
    storageBucket: 'zingoo-823df.firebasestorage.app',
    measurementId: 'G-87B2W2K1D1',
  );
}
